display_icon_titles:
  default: true
  description:
    en: "Display titles"

icons_size:
  default: 1.7
  description:
    en: "This setting changes the CSS font-size property of the icons (unit is em)"

tab_1_settings:
  default: "Kezdőoldal, home, /"
  description:
    en: "Format is: <code>&lt;title&gt;, &lt;FA5 icon&gt;, &lt;relative url or route name&gt;, &lt;enabled? default true (optional)&gt;</code>"

tab_2_settings:
  default: "Portfólióm, layer-group, /my/activity/portfolio"

tab_3_settings:
  default: "Új téma, plus-square, https://vaperina.cc/new-topic"

tab_4_settings:
  default: "Üzenetek, envelope, userPrivateMessages"

tab_5_settings:
  default: "Hirdetések, tags, /c/adok-veszek/31"

tab_6_settings:
  default: "Notifications, comment, userNotifications, false"

extend_fa5_icons:
  type: list
  default: ""
  description:
    en: "Use this setting to add any icons you want to use that are not included in the default FA5 icons subset"
